version: "3.3"
services:
  pihole:
    container_name: pihole
    hostname: pi-hole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8081:80/tcp"

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${PIHOLE_HOME}/pihole/:/etc/pihole/
      - ${PIHOLE_HOME}/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
